baseURL = "https://zzzzzy2k.github.io/"
locale = "zh-cn"
defaultContentLanguage = "zh"
title = "zzzzzy2k 的博客"
theme = "stack"
[pagination]
  pagerSize = 5
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "monokai"
