[[main]]
    identifier = "home"
    name       = "首页"
    url        = "/"
    weight     = 1

    [main.params]
        icon = "home"

[[main]]
    identifier = "archives"
    name       = "归档"
    url        = "/archives/"
    weight     = 2

    [main.params]
        icon = "archives"

[[main]]
    identifier = "tags"
    name       = "标签"
    url        = "/tags/"
    weight     = 3

    [main.params]
        icon = "tag"

[[main]]
    identifier = "about"
    name       = "关于"
    url        = "/about/"
    weight     = 4

    [main.params]
        icon = "user"

[[main]]
    identifier = "projects"
    name       = "项目"
    url        = "/projects/"
    weight     = 5

    [main.params]
        icon = "link"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/zzzzzy2k"

    [social.params]
        icon = "brand-github"
