mainSections = ["posts"]
defaultTheme = "auto"
robots = true

[sidebar]
  emoji = "📖"
  subtitle = "记录技术与生活"
  avatar = "https://github.com/zzzzzy2k.png"
  [sidebar.posts]
    limit = 5

[article]
  toc = true
  readingTime = true
  license = { enabled = false }

[widget]
  [widget.social]
    enabled = true

[footer]
  since = 2026

[comments]
  enabled = false

[readingTime]
  enabled = true

[seo]
  [seo.title]
    separator = " - "
